const faker = require('faker');

const eventsData = [
  {
    title: "Mother's Day Celebration - Apron Design & Cake Decorating",
    host: 'MERAKI on Move',
    categoryId: 1,
    image: "https://aevent-project.s3.amazonaws.com/1-mothersDay.jpg",
    description: faker.lorem.paragraphs(4),
    city: faker.address.city(),
    state: faker.address.state(),
    dateAndTime: faker.date.future(),
    totalTickets: 10,
    ticketPrice: 25.00,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: "Mother's Day Make + Take Essential Oils Class",
    host: 'NJ Metta Yoga',
    categoryId: 1,
    image: "https://aevent-project.s3.amazonaws.com/2-mothersDay.jpg",
    description: faker.lorem.paragraphs(5),
    city: faker.address.city(),
    state: faker.address.state(),
    dateAndTime: faker.date.future(),
    totalTickets: 10,
    ticketPrice: 35.00,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: "Mother's Day Brunch & Dinner",
    host: "Delta's Restaurant",
    categoryId: 1,
    image: "https://aevent-project.s3.amazonaws.com/3-mothersDay.jpg",
    description: faker.lorem.paragraphs(4),
    city: faker.address.city(),
    state: faker.address.state(),
    dateAndTime: faker.date.future(),
    totalTickets: 10,
    ticketPrice: 105.00,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: "The Art of Bonsai: Cutting and Wiring",
    host: 'Calgo Gardens',
    categoryId: 2,
    image: "https://aevent-project.s3.amazonaws.com/4-free.jpg",
    description: faker.lorem.paragraphs(5),
    city: faker.address.city(),
    state: faker.address.state(),
    dateAndTime: faker.date.future(),
    totalTickets: 10,
    ticketPrice: 0.00,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: "Free Cooking Class: Clean Eating Made Simple",
    host: "Nature's Corner Market",
    categoryId: 2,
    image: "https://aevent-project.s3.amazonaws.com/5-free.jpg",
    description: faker.lorem.paragraphs(5),
    city: faker.address.city(),
    state: faker.address.state(),
    dateAndTime: faker.date.future(),
    totalTickets: 10,
    ticketPrice: 0.00,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: "ODESZA Bright Night Glow Concert",
    host: 'B&O Railroad Museum',
    categoryId: 3,
    image: "https://aevent-project.s3.amazonaws.com/6-music.jpg",
    description: faker.lorem.paragraphs(5),
    city: faker.address.city(),
    state: faker.address.state(),
    dateAndTime: faker.date.future(),
    totalTickets: 10,
    ticketPrice: 35.00,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: "Cherub Tour",
    host: 'Camp City',
    categoryId: 3,
    image: "https://aevent-project.s3.amazonaws.com/7-music.jpg",
    description: faker.lorem.paragraphs(4),
    city: faker.address.city(),
    state: faker.address.state(),
    dateAndTime: faker.date.future(),
    totalTickets: 10,
    ticketPrice: 50.00,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: "Frank Sinatra Concert Collection",
    host: 'Donna Cardillo',
    categoryId: 3,
    image: "https://aevent-project.s3.amazonaws.com/8-music.jpg",
    description: faker.lorem.paragraphs(5),
    city: faker.address.city(),
    state: faker.address.state(),
    dateAndTime: faker.date.future(),
    totalTickets: 10,
    ticketPrice: 65.00,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: "One Day of Electronic Dance Music",
    host: 'BB&T',
    categoryId: 3,
    image: "https://aevent-project.s3.amazonaws.com/9-music.jpg",
    description: faker.lorem.paragraphs(5),
    city: faker.address.city(),
    state: faker.address.state(),
    dateAndTime: faker.date.future(),
    totalTickets: 10,
    ticketPrice: 25.00,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: "The Billy Joel Rendition",
    host: 'Trevor Hall',
    categoryId: 3,
    image: "https://aevent-project.s3.amazonaws.com/10-music.jpg",
    description: faker.lorem.paragraphs(5),
    city: faker.address.city(),
    state: faker.address.state(),
    dateAndTime: faker.date.future(),
    totalTickets: 10,
    ticketPrice: 65.00,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: "Tomorrowland 2021",
    host: "Belgian Electronic",
    categoryId: 4,
    image: "https://aevent-project.s3.amazonaws.com/11-music.jpg",
    description: faker.lorem.paragraphs(6),
    city: faker.address.city(),
    state: faker.address.state(),
    dateAndTime: faker.date.future(),
    totalTickets: 10,
    ticketPrice: 320.00,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: "EDC Las Vegas 2021",
    host: "Nevada Venue",
    categoryId: 4,
    image: "https://aevent-project.s3.amazonaws.com/12-music.jpg",
    description: faker.lorem.paragraphs(5),
    city: faker.address.city(),
    state: faker.address.state(),
    dateAndTime: faker.date.future(),
    totalTickets: 10,
    ticketPrice: 190.00,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: "Lollapalooza 2021",
    host: "The Windy City",
    categoryId: 4,
    image: "https://aevent-project.s3.amazonaws.com/13-music.jpg",
    description: faker.lorem.paragraphs(4),
    city: faker.address.city(),
    state: faker.address.state(),
    dateAndTime: faker.date.future(),
    totalTickets: 10,
    ticketPrice: 120.00,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: "Ultra Miami Music Festival",
    host: "Delaware County",
    categoryId: 4,
    image: "https://aevent-project.s3.amazonaws.com/14-music.jpg",
    description: faker.lorem.paragraphs(4),
    city: faker.address.city(),
    state: faker.address.state(),
    dateAndTime: faker.date.future(),
    totalTickets: 10,
    ticketPrice: 260.00,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: "FLOAT FEST",
    host: "San Marcos TX Venue",
    categoryId: 4,
    image: "https://aevent-project.s3.amazonaws.com/15-music.jpg",
    description: faker.lorem.paragraphs(5),
    city: faker.address.city(),
    state: faker.address.state(),
    dateAndTime: faker.date.future(),
    totalTickets: 10,
    ticketPrice: 170.00,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: "Electric Forest Festival",
    host: "Billy Kimber Stadium",
    categoryId: 4,
    image: "https://aevent-project.s3.amazonaws.com/16-music.jpg",
    description: faker.lorem.paragraphs(4),
    city: faker.address.city(),
    state: faker.address.state(),
    dateAndTime: faker.date.future(),
    totalTickets: 10,
    ticketPrice: 210.00,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: "Sushi Making 101",
    host: "Soule' Culinary Art Studio",
    categoryId: 5,
    image: "https://aevent-project.s3.amazonaws.com/17-food.jpg",
    description: faker.lorem.paragraphs(5),
    city: faker.address.city(),
    state: faker.address.state(),
    dateAndTime: faker.date.future(),
    totalTickets: 10,
    ticketPrice: 65.00,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: "Crawfish Boil Festival",
    host: 'Long Wharf Park',
    categoryId: 5,
    image: "https://aevent-project.s3.amazonaws.com/18-food.jpg",
    description: faker.lorem.paragraphs(4),
    city: faker.address.city(),
    state: faker.address.state(),
    dateAndTime: faker.date.future(),
    totalTickets: 10,
    ticketPrice: 20.00,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: "Cocktails and Wine: 2nd Street",
    host: 'Peter Station',
    categoryId: 5,
    image: "https://aevent-project.s3.amazonaws.com/19-food.jpg",
    description: faker.lorem.paragraphs(4),
    city: faker.address.city(),
    state: faker.address.state(),
    dateAndTime: faker.date.future(),
    totalTickets: 10,
    ticketPrice: 65.00,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: "Food Truck Craze: Spring Edition",
    host: 'Ridge Ave',
    categoryId: 5,
    image: "https://aevent-project.s3.amazonaws.com/20-food.jpg",
    description: faker.lorem.paragraphs(4),
    city: faker.address.city(),
    state: faker.address.state(),
    dateAndTime: faker.date.future(),
    totalTickets: 10,
    ticketPrice: 65.00,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: "Happy Hour Historic Food Tour",
    host: 'Passyunk Corp.',
    categoryId: 5,
    image: "https://aevent-project.s3.amazonaws.com/21-food.jpg",
    description: faker.lorem.paragraphs(4),
    city: faker.address.city(),
    state: faker.address.state(),
    dateAndTime: faker.date.future(),
    totalTickets: 10,
    ticketPrice: 65.00,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: "Chef's Tasting Brunch",
    host: 'Catering Company',
    categoryId: 5,
    image: "https://aevent-project.s3.amazonaws.com/22-food.jpg",
    description: faker.lorem.paragraphs(4),
    city: faker.address.city(),
    state: faker.address.state(),
    dateAndTime: faker.date.future(),
    totalTickets: 10,
    ticketPrice: 65.00,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: "Brunch in Dallasbasas",
    host: 'Mesa Grill',
    categoryId: 5,
    image: "https://aevent-project.s3.amazonaws.com/23-food.jpg",
    description: faker.lorem.paragraphs(4),
    city: faker.address.city(),
    state: faker.address.state(),
    dateAndTime: faker.date.future(),
    totalTickets: 10,
    ticketPrice: 65.00,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: "",
    host: 'Hello',
    categoryId: 6,
    image: faker.image.people(),
    description: faker.lorem.paragraphs(4),
    city: faker.address.city(),
    state: faker.address.state(),
    dateAndTime: faker.date.future(),
    totalTickets: 10,
    ticketPrice: 5.00,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: faker.lorem.words(4),
    host: 'Hello',
    categoryId: 7,
    image: faker.image.people(),
    description: faker.lorem.paragraphs(4),
    city: faker.address.city(),
    state: faker.address.state(),
    dateAndTime: faker.date.future(),
    totalTickets: 10,
    ticketPrice: 5.00,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    title: faker.lorem.words(4),
    host: 'Hello',
    categoryId: 8,
    image: faker.image.people(),
    description: faker.lorem.paragraphs(4),
    city: faker.address.city(),
    state: faker.address.state(),
    dateAndTime: faker.date.future(),
    totalTickets: 10,
    ticketPrice: 5.00,
    createdAt: new Date(),
    updatedAt: new Date()
  },
]

const ticketsData = [
  { eventId: 1, userId: 10 },
  { eventId: 2, userId: 11 },
  { eventId: 3, userId: 12 },
  { eventId: 4, userId: 13 },
  { eventId: 5, userId: 14 },
  { eventId: 6, userId: 15 },
  { eventId: 7, userId: 16 },
  { eventId: 8, userId: 17 },
  { eventId: 2, userId: 18 },
];

const favoritesData = [
  { eventId: 1, userId: 10 },
  { eventId: 2, userId: 11 },
  { eventId: 3, userId: 12 },
  { eventId: 4, userId: 13 },
  { eventId: 5, userId: 14 },
  { eventId: 6, userId: 15 },
  { eventId: 7, userId: 16 },
  { eventId: 8, userId: 17 },
  { eventId: 2, userId: 18 },
];

module.exports = {
  eventsData,
  ticketsData,
  favoritesData
}